### ISSUE TITLE
s/S does not jump vertically

### ISSUE THREAD

**Issue by jannes** [Mishkun/ideavim-sneak#5]
Hey,

Thanks for your work first of all.
I installed this right away because I've been missing the functionality of sneak for some time now.

However, the behavior of the forward and backward jump is not correct,
it is supposed to also search vertically, but this plugin only searches within the same line.

**Comment by Mishkun** [comment]
Yeah, I narrowed search to the one line to behave it more like [vim-seek](https://github.com/goldfeld/vim-seek) plugin, because I already use [AceJump](https://github.com/acejump/AceJump) integration for jumping across lines. Guess I might add an option to enable vertical jumps too. It should be easy to do once I learn how to search only visible lines and not the whole file (which can be crazy)

**Comment by jannes** [comment]
I'll prepare a PR to make the jumps vertical

**Comment by Mishkun** [comment]
Kudos for you! Cleaned my test suite and added a basic CI to help you with this
